# package.json repo à changer

tasks:
  - name: install all dependencies
    init: |
      npm install -g ts-node
      yarn add -D typescript @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint eslint-config-next
      yarn add -D jest-cucumber
      yarn add -D @types/react @types/node
      yarn add -D postcss@latest tailwindcss@latest autoprefixer@latest
      yarn add next react react-dom  && echo -e "/// <reference types=\"next\" />\n/// <reference types=\"next/types/global\" />\n/// <reference types=\"next/image-types/global\" />\ndeclare module '*.css'" > next-env.d.ts
      yarn add nanoid
      npx tailwindcss init -p

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-ceintl.vscode-language-pack-fr
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - graphql.vscode-graphql
    - kavod-io.vscode-jest-test-adapter
    - pkief.material-icon-theme
    - esbenp.prettier-vscode
    - yatki.vscode-surround
    - bradlc.vscode-tailwindcss
    - hbenl.vscode-test-explorer
    - fabiospampinato.vscode-todo-plus
    - dbaeumer.vscode-eslint
    - tabnine.tabnine-vscode
    - codezombiech.gitignore
    - foxundermoon.shell-format
